"""Generic ancestral-DDPM runner family implementation."""

from __future__ import annotations

from pathlib import Path
from typing import Any, Mapping, Sequence

import torch

from reference_cache import checkpoint_fingerprint
from runners.base import BaseRunner
from runners.ddpm.sampling import (
    DDPM,
    resolve_split_percentages as _diffusion_resolve_split_percentages,
    run_solver_baseline_batch,
    sample_segment as _diffusion_sample_segment,
)

DDPM_TIMESTEP_SPACINGS = frozenset({"leading", "linspace", "trailing"})
DDPM_SCHEDULER_KEYS = frozenset(
    {
        "beta_start",
        "beta_end",
        "beta_schedule",
        "trained_betas",
        "variance_type",
        "clip_sample",
        "clip_sample_range",
        "prediction_type",
        "thresholding",
        "dynamic_thresholding_ratio",
        "sample_max_value",
        "timestep_spacing",
        "steps_offset",
        "rescale_betas_zero_snr",
    }
)


def _json_safe(value):
    if isinstance(value, dict):
        return {str(k): _json_safe(v) for k, v in value.items()}
    if isinstance(value, (list, tuple)):
        return [_json_safe(v) for v in value]
    if hasattr(value, "tolist"):
        return value.tolist()
    if isinstance(value, (int, float, str, bool)) or value is None:
        return value
    return str(value)


def stable_scheduler_config(config):
    """The behavior-defining scheduler settings, as they enter ``target_spec``."""
    raw = dict(config)
    keys = DDPM_SCHEDULER_KEYS | {"num_train_timesteps"}
    return _json_safe({key: raw.get(key) for key in sorted(keys) if key in raw})


def resolved_hf_revision(pipe) -> str | None:
    """Resolve a cached Hugging Face snapshot revision without network access."""
    direct = getattr(pipe, "_commit_hash", None)
    if direct:
        return str(direct)
    unet_config = getattr(getattr(pipe, "unet", None), "config", None)
    source = getattr(unet_config, "_name_or_path", None)
    if source:
        snapshot = Path(str(source))
        if snapshot.parent.name == "snapshots" and snapshot.name:
            return snapshot.name
    return None


class DDPMRunner(BaseRunner):
    """Ancestral DDPM sampling; subclasses load the model and own postprocessing."""

    runner_name = "ddpm"
    supported_samplers: Sequence[str] = ()
    # Method name for reference samples generated by the model itself.
    reference_method = "ddpm_samples"

    def __init__(
        self,
        *,
        model,
        target_spec: Mapping[str, Any],
        T: int,
        sampling_steps: int,
        sampler: str = "ddpm",
        timestep_spacing: str | None = None,
        device: str,
        checkpoint_path: str | None = None,
    ):
        sampler = str(sampler)
        if sampler not in type(self).supported_samplers:
            raise ValueError(
                f"Unknown DDPM sampler {sampler!r}. "
                f"Available: {tuple(type(self).supported_samplers)}"
            )
        self._model = model
        self._target_spec = dict(target_spec)
        self._T = int(T)
        self._sampling_steps = int(sampling_steps)
        self._sampler = sampler
        self._device = str(device)
        self._checkpoint_path = checkpoint_path or type(self).default_checkpoint_path()
        scheduler_config = dict(self._target_spec.get("scheduler_config") or {})
        configured_T = scheduler_config.get("num_train_timesteps")
        if configured_T is not None and int(configured_T) != self._T:
            raise ValueError(
                "DDPM T must match the checkpoint scheduler: "
                f"{self._T} != {int(configured_T)}"
            )
        ddpm_kwargs = {
            key: scheduler_config[key]
            for key in DDPM_SCHEDULER_KEYS
            if scheduler_config.get(key) is not None
        }
        if timestep_spacing is not None:
            ddpm_kwargs["timestep_spacing"] = str(timestep_spacing)
        self._timestep_spacing = str(ddpm_kwargs.get("timestep_spacing", "leading"))
        self._ddpm = DDPM(
            T=self._T,
            device=self._device,
            sampling_steps=self._sampling_steps,
            **ddpm_kwargs,
        )

    @classmethod
    def load_model(cls, device: str, *, no_compile: bool):
        """Return ``(model, target_spec)``."""
        raise NotImplementedError(f"{cls.__name__}.load_model must be implemented")

    @staticmethod
    def model_input_dim(model) -> int:
        raise NotImplementedError("DDPM subclasses must implement model_input_dim")

    @classmethod
    def load_from_checkpoint(
        cls,
        checkpoint_path: str | None = None,
        *,
        device: str,
        no_compile: bool = False,
        T: int | None = None,
        sampling_steps: int | None = None,
        sampler: str = "ddpm",
        timestep_spacing: str | None = None,
        **kwargs,
    ) -> "DDPMRunner":
        if kwargs:
            raise ValueError(
                f"{cls.__name__}.load_from_checkpoint got unknown keys: "
                f"{sorted(kwargs)}"
            )
        model, target_spec = cls.load_model(device, no_compile=no_compile)
        if T is None:
            scheduler_config = dict(target_spec.get("scheduler_config") or {})
            T = int(scheduler_config.get("num_train_timesteps") or 1000)
        if sampling_steps is None:
            sampling_steps = int(T)
        return cls(
            model=model,
            target_spec=target_spec,
            T=int(T),
            sampling_steps=int(sampling_steps),
            sampler=sampler,
            timestep_spacing=timestep_spacing,
            device=device,
            checkpoint_path=checkpoint_path or cls.default_checkpoint_path(),
        )

    def with_sampling_config(self, **kwargs) -> "DDPMRunner":
        allowed = {"sampler", "T", "sampling_steps", "timestep_spacing"}
        unknown = set(kwargs) - allowed
        if unknown:
            raise ValueError(
                f"{type(self).__name__}.with_sampling_config got unknown keys: "
                f"{sorted(unknown)}"
            )
        return type(self)(
            model=self._model,
            target_spec=self._target_spec,
            T=int(kwargs.get("T", self._T)),
            sampling_steps=int(kwargs.get("sampling_steps", self._sampling_steps)),
            sampler=str(kwargs.get("sampler", self._sampler)),
            timestep_spacing=str(kwargs.get("timestep_spacing", self._timestep_spacing)),
            device=self._device,
            checkpoint_path=self._checkpoint_path,
        )

    @property
    def input_dim(self) -> int:
        return int(type(self).model_input_dim(self._model))

    @property
    def sample_dim(self) -> int:
        """Dimension after terminal postprocessing (possibly decoding)."""
        return int(self._target_spec.get("sample_dim", self.input_dim))

    def sampling_cache_key(self) -> Mapping[str, Any]:
        return {
            "sampler": str(self._sampler),
            "T": int(self._T),
            "sampling_steps": int(self._sampling_steps),
            "timestep_spacing": str(self._timestep_spacing),
        }

    @property
    def start_time(self) -> Any:
        return int(self._T)

    @property
    def end_time(self) -> Any:
        return 0

    def sample_prior(self, num_samples: int, *, generator=None) -> torch.Tensor:
        return torch.randn(
            int(num_samples),
            self.input_dim,
            device=self._device,
            generator=generator,
        )

    def sample_segment(
        self,
        x: torch.Tensor,
        start_time: Any,
        end_time: Any,
        *,
        generator=None,
        progress_callback=None,
    ) -> torch.Tensor:
        return _diffusion_sample_segment(
            self._ddpm,
            self._model,
            x,
            int(start_time),
            int(end_time),
            generator=generator,
            progress_callback=progress_callback,
        )

    def resolve_split_percentages(self, split_percentages: Sequence[float]):
        return _diffusion_resolve_split_percentages(self._ddpm, split_percentages)

    def segment_cost(self, start_time: Any, end_time: Any) -> float:
        return float(self._ddpm.segment_cost(int(start_time), int(end_time)))

    def _split_point(self, point):
        return int(point)

    def parse_solver_baseline_name(self, name: str, solver: str) -> dict | None:
        prefix = f"{solver}_"
        rest = name[len(prefix) :].split("_") if name.startswith(prefix) else []
        has_eta = (
            len(rest) == 1 and rest[0].startswith("eta")
        ) or (
            len(rest) == 2 and rest[1].startswith("eta")
        )
        if solver != "ddim" or not has_eta:
            parsed = super().parse_solver_baseline_name(name, solver)
            if parsed is not None or solver != "ddim":
                return parsed
        if not name.startswith(prefix):
            return None
        if len(rest) == 1 and rest[0].startswith("eta") and rest[0] != "eta":
            step_token = None
            eta_token = rest[0]
        elif len(rest) == 2 and rest[1].startswith("eta") and rest[1] != "eta":
            step_token = rest[0]
            eta_token = rest[1]
        else:
            return None
        try:
            steps = None if step_token is None else int(step_token)
            eta = float(eta_token[3:])
        except ValueError as exc:
            raise ValueError(f"baseline {name!r} has bad ddim solver syntax") from exc
        if steps is not None and steps < 1:
            raise ValueError(f"baseline {name!r} must use steps >= 1")
        return self._solver_baseline_spec(name, solver, steps, eta=eta)

    def solver_cost(self, solver: str, **solver_kwargs) -> float:
        if solver not in type(self).supported_solvers:
            raise ValueError(f"Unknown solver '{solver}'")
        sampling_steps = solver_kwargs.get("sampling_steps", self._sampling_steps)
        return float(int(sampling_steps))

    def solver_cache_key(self, solver: str, **solver_kwargs) -> Mapping[str, Any]:
        if solver not in type(self).supported_solvers:
            raise ValueError(f"Unknown solver '{solver}'")
        key: dict[str, Any] = {}
        if "sampling_steps" in solver_kwargs:
            key["sampling_steps"] = int(solver_kwargs["sampling_steps"])
        if solver == "ddim" and float(solver_kwargs.get("eta", 0.0)) != 0.0:
            key["eta"] = float(solver_kwargs["eta"])
        for name in sorted(set(solver_kwargs) - set(key) - {"eta"}):
            key[name] = solver_kwargs[name]
        return key

    def schedule_cost(self) -> float:
        return float(int(self._sampling_steps))

    def run_solver_baseline_batch(
        self,
        *,
        solver: str,
        chunk_size: int,
        n0: int,
        generator=None,
        max_sampling_batch_size=None,
        **solver_kwargs,
    ):
        return run_solver_baseline_batch(
            model=self._model,
            postprocess_fn=self.postprocess_samples,
            solver=solver,
            chunk_size=chunk_size,
            n0=n0,
            T=int(solver_kwargs.get("T", self._T)),
            sampling_steps=int(solver_kwargs.get("sampling_steps", self._sampling_steps)),
            eta=float(solver_kwargs.get("eta", 0.0)),
            device=self._device,
            generator=generator,
            max_sampling_batch_size=max_sampling_batch_size,
        )

    def normalize_reference_generation_config(
        self,
        comparison_mode: str,
        reference_generation_config: Mapping[str, Any] | None,
    ) -> Mapping[str, Any]:
        self.comparison_mode_spec(comparison_mode)
        if reference_generation_config is None:
            raise ValueError(
                f"reference_generation_config is required for comparison_mode={comparison_mode!r}"
            )
        cfg = dict(reference_generation_config)
        method = type(self).reference_method
        required = {"method", "sampler", "T", "sampling_steps"}
        missing = sorted(required - set(cfg))
        if missing:
            raise ValueError(
                f"reference_generation_config missing required keys: {missing}"
            )
        unknown = set(cfg) - required - {"timestep_spacing", "seed"}
        if unknown:
            raise ValueError(
                f"Unknown reference_generation_config keys: {sorted(unknown)}"
            )
        if str(cfg["method"]) != method:
            raise ValueError(
                "reference_generation_config must set "
                f"method={method!r}, got {cfg['method']!r}"
            )
        sampler = str(cfg["sampler"])
        if sampler not in type(self).supported_samplers:
            raise ValueError(
                f"Unknown DDPM reference sampler {sampler!r}. "
                f"Available: {tuple(type(self).supported_samplers)}"
            )
        T = int(cfg["T"])
        sampling_steps = int(cfg["sampling_steps"])
        if T < 1:
            raise ValueError("DDPM reference T must be at least 1")
        if sampling_steps < 1:
            raise ValueError("DDPM reference sampling_steps must be at least 1")
        if sampling_steps > T:
            raise ValueError("DDPM reference sampling_steps cannot exceed T")
        scheduler_T = (self._target_spec.get("scheduler_config") or {}).get(
            "num_train_timesteps"
        )
        if scheduler_T is None:
            raise ValueError(
                f"Loaded {self.runner_name} target is missing scheduler num_train_timesteps"
            )
        if T != int(scheduler_T):
            raise ValueError(
                f"{self.runner_name} reference T must match the loaded scheduler "
                f"({int(scheduler_T)}), got {T}"
            )
        timestep_spacing = str(cfg.get("timestep_spacing", self._timestep_spacing))
        if timestep_spacing not in DDPM_TIMESTEP_SPACINGS:
            raise ValueError(
                f"Unknown DDPM timestep_spacing {timestep_spacing!r}. "
                f"Available: {tuple(sorted(DDPM_TIMESTEP_SPACINGS))}"
            )
        seed = int(cfg.get("seed", 0))
        if seed < 0:
            raise ValueError("reference seed must be nonnegative")
        return {
            "method": method,
            "sampler": sampler,
            "T": T,
            "sampling_steps": sampling_steps,
            "timestep_spacing": timestep_spacing,
            "seed": seed,
        }

    def reference_cache_key(
        self,
        comparison_mode: str,
        reference_generation_config: Mapping[str, Any] | None = None,
    ) -> Mapping[str, Any]:
        ref_cfg = self.normalize_reference_generation_config(
            comparison_mode, reference_generation_config
        )
        key = {
            "runner": self.runner_name,
            "comparison_mode": comparison_mode,
            "target_spec": self._target_spec,
            "reference_generation_config": dict(ref_cfg),
        }
        if ref_cfg.get("method") in {"ddpm_samples", "hf_ddpm_scheduler"}:
            fingerprint = checkpoint_fingerprint(self._checkpoint_path)
            if fingerprint is not None:
                key["checkpoint_fingerprint"] = fingerprint
        return key

    def generate_reference_samples(
        self,
        *,
        comparison_mode: str,
        reference_generation_config: Mapping[str, Any],
        num_samples: int,
        batch_size: int,
        generator=None,
        progress=None,
    ) -> torch.Tensor:
        ref_cfg = self.normalize_reference_generation_config(
            comparison_mode, reference_generation_config
        )
        if batch_size < 1 or num_samples < 1:
            raise ValueError("Reference batch_size and num_samples must be positive")
        ref_runner = self.with_sampling_config(
            sampler=ref_cfg["sampler"],
            T=ref_cfg["T"],
            sampling_steps=ref_cfg["sampling_steps"],
            timestep_spacing=ref_cfg["timestep_spacing"],
        )
        return ref_runner._sample_reference(
            num_samples,
            batch_size,
            sample_dim=ref_runner.sample_dim,
            num_steps=ref_runner._ddpm.segment_cost(ref_runner._T, 0),
            generator=generator,
            progress=progress,
        )
